server:
  port: 8888
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  jmx:
    enabled: false
  application:
    name: API-Gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
      routes:
        - id: finance-service
          uri: lb://Finance
          predicates:
            - Path=/finance/**
          filters:
        - id: User-service
          uri: lb://User
          predicates:
            - Path=/user/**
          filters:
            - name: APILoginFilter
            - name: TokenCheckFilter
        - id: Attendance-service
          uri: lb://Attendance
          predicates:
            - Path=/attendance/**


