server:
  port: 8888

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  jmx:
    enabled: false
  application:
    name: API-Gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lowerCaseServiceId: true
          cache:   # Fixed typo here
            enabled: false
      routes:
        - id: finance-service
          uri: lb://Finance
          predicates:
            - Path=/finance/**
          
        - id: user-login-service
          uri: lb://User
          predicates:
            - Path=/user/login

        - id: User-service
          uri: lb://User
          predicates:
            - Path=/user/**
          filters:
            - TokenCheckFilter
        - id: Attendance-service
          uri: lb://Attendance
          predicates:
            - Path=/attendance/**

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
