server:
  port: 6060
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Attendance
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/attendance
    username: user
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always
    job:
      enabled: false
  jpa:           # 이 부분이 잘못되었었습니다
    show-sql: true
