server:
  port: 6060
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: Attendance
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/attendance
    username: user
    password: 1234 #코딩하는 사람 맞춰서 db 아이디 , 변경, 위 url의 db명 변경하여 사용하기~
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    jdbc:
      initialize-schema: always  # Spring Batch 테이블 자동 생성
    job:
      enabled: false  # Job 자동 실행 방지
    datasource:
    url: jdbc:mysql://localhost:3307/batch
    username: user
    password: 1234 #코딩하는 사람 맞춰서 db 아이디 , 변경, 위 url의 db명 변경하여 사용하기~
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
