server:
 port: 6060
eureka:
 client:
   register-with-eureka: true
   fetch-registry: true
   service-url:
     defaultZone: http://localhost:8761/eureka
spring:
 application:
   name: Attendance
 cloud:
   config:
     enabled: false
 datasource:
   url: jdbc:mysql://localhost:3307/attendance?createDatabaseIfNotExist=true
   username: user
   password: 1234
   driver-class-name: com.mysql.cj.jdbc.Driver
 sql:
   init:
     mode: always
 batch:
   jdbc:
     initialize-schema: always
     table-prefix: BATCH_
   job:
     enabled: false
 jpa:
   show-sql: true
   defer-datasource-initialization: true
   hibernate:
     ddl-auto: update
   properties:
     hibernate:
       format_sql: true
