server:
  port: 7070
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: j525252p@gmail.com
    password: lfyywzrymhinrbug
    properties:
      mail:
        smtp:
          auth: true # 5
          timeout: 5000 # 6
          starttls:
            enable: true # 7
  application:
    name: User
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:mysql://localhost:3307/member
    username: user
    password: 1234 #코딩하는 사람 맞춰서 db 아이디 , 변경, 위 url의 db명 변경하여 사용하기~
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
